"""Official Python SDK for the SkyLink API.

Quickstart::

    from skylink_api import SkyLink

    with SkyLink(api_key="...") as sky:
        metar = sky.weather.metar("KJFK", parsed=True)
        flights = sky.adsb.aircraft(lat=40.6, lon=-73.8, radius=50)
        status = sky.flight_status("BA123")

Async mirrors the sync surface one-for-one::

    from skylink_api import AsyncSkyLink

    async with AsyncSkyLink(api_key="...") as sky:
        metar = await sky.weather.metar("KJFK")

Everything a caller needs lives at the top level: the two clients, the error
hierarchy, the configuration types and every response model. Resource classes
are reached through a client instance, but can be imported from
:mod:`skylink_api.resources` when you need them for annotations.
"""

from . import helpers
from ._client import AsyncSkyLink, SkyLink
from ._constants import (
    CHART_CATEGORIES,
    CONTINENTS,
    FLIGHT_CATEGORIES,
    HISTORY_PLANS,
    WEBHOOK_EVENTS,
)
from ._exceptions import (
    APIConnectionError,
    APIResponseValidationError,
    APIStatusError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    InternalServerError,
    NotFoundError,
    PermissionDeniedError,
    RateLimitError,
    ServiceUnavailableError,
    SkyLinkError,
    UnprocessableEntityError,
    ValidationErrorItem,
)
from ._response import RateLimitInfo
from ._types import BBox, HistoryPlan, Provider, RequestOptions
from ._version import __version__
from .helpers.cache import CacheProtocol, MemoryCache
from .models import (
    AdsbAircraft,
    AdsbAircraftList,
    AdsbAltitudeStats,
    AdsbDiff,
    AdsbHealth,
    AdsbStatistics,
    AircraftDatabaseStats,
    AircraftDetails,
    AircraftLookup,
    AircraftPerformance,
    AircraftPhoto,
    Airline,
    AirlineRoute,
    AirlineRoutesResult,
    Airport,
    AirportBrief,
    AirportBriefing,
    AirportFrequency,
    AirportRoutesResponse,
    AirportsByIPResponse,
    AirportsByLocationResponse,
    AirportSearchLocation,
    AirportsTextSearchResponse,
    AirportWithDistance,
    AirportWithRelevance,
    AirSigmetCoord,
    AirSigmetMovement,
    AirSigmetObservation,
    AirSigmetReport,
    AirSigmetResponse,
    AirspaceFlowProgram,
    ArrivalFlight,
    ArrivalsResponse,
    BriefingNotam,
    BriefingPirep,
    BriefingRestriction,
    BriefingWeather,
    CallsignRoute,
    CarbonEstimate,
    Chart,
    ChartSource,
    ChartSourcesResponse,
    ChartsResponse,
    Closure,
    CloudLayer,
    Coordinates,
    CountriesResponse,
    Country,
    CountryDetail,
    DepartureFlight,
    DeparturesResponse,
    DistanceResponse,
    EnrichedAircraft,
    EnrichedAirport,
    FaaDelayResponse,
    FlightBrief,
    FlightBriefing,
    FlightBriefingText,
    FlightStatusArrival,
    FlightStatusDeparture,
    FlightStatusLeg,
    FlightStatusResponse,
    FlightTimePrediction,
    GroundDelay,
    GroundStop,
    HistoryAirportTrafficResponse,
    HistoryFilters,
    HistoryFlight,
    HistoryFlightsResponse,
    HistoryPosition,
    HistoryPositionsResponse,
    HistoryTrackResponse,
    IPLocation,
    Layover,
    Metar,
    MetarParsed,
    MetarWithParsed,
    Navaid,
    NavaidsResponse,
    NotamEntry,
    NotamsResponse,
    Number,
    PirepReport,
    PirepsResponse,
    Region,
    RegionDetail,
    RegionsResponse,
    RouteBrief,
    RoutePair,
    RoutePairsResponse,
    Runway,
    ScheduleFlight,
    ScheduleResponse,
    ScheduleWithStatus,
    SkyLinkModel,
    Taf,
    TafParsed,
    TafPeriod,
    TafWithParsed,
    TicketLeg,
    TicketOffer,
    TicketSearchResponse,
    Visibility,
    VrsRouteResult,
    WeatherReport,
    Webhook,
    WebhookEventTypesResponse,
    WebhookListResponse,
    WebhookSubscription,
    WebhookToggleResponse,
    Wind,
    WindLevel,
    WindsAloftResponse,
    WindsAloftStation,
    WxCode,
)
from .models.webhooks import WebhookEvent

# Plain lexicographic order (asserted by ``tests/test_exports.py``), not ruff's
# isort-style grouping, which would float the SCREAMING_CASE constants to the top.
__all__ = [  # noqa: RUF022
    "APIConnectionError",
    "APIResponseValidationError",
    "APIStatusError",
    "APITimeoutError",
    "AdsbAircraft",
    "AdsbAircraftList",
    "AdsbAltitudeStats",
    "AdsbDiff",
    "AdsbHealth",
    "AdsbStatistics",
    "AirSigmetCoord",
    "AirSigmetMovement",
    "AirSigmetObservation",
    "AirSigmetReport",
    "AirSigmetResponse",
    "AircraftDatabaseStats",
    "AircraftDetails",
    "AircraftLookup",
    "AircraftPerformance",
    "AircraftPhoto",
    "Airline",
    "AirlineRoute",
    "AirlineRoutesResult",
    "Airport",
    "AirportBrief",
    "AirportBriefing",
    "AirportFrequency",
    "AirportRoutesResponse",
    "AirportSearchLocation",
    "AirportWithDistance",
    "AirportWithRelevance",
    "AirportsByIPResponse",
    "AirportsByLocationResponse",
    "AirportsTextSearchResponse",
    "AirspaceFlowProgram",
    "ArrivalFlight",
    "ArrivalsResponse",
    "AsyncSkyLink",
    "AuthenticationError",
    "BBox",
    "BadRequestError",
    "BriefingNotam",
    "BriefingPirep",
    "BriefingRestriction",
    "BriefingWeather",
    "CHART_CATEGORIES",
    "CONTINENTS",
    "CacheProtocol",
    "CallsignRoute",
    "CarbonEstimate",
    "Chart",
    "ChartSource",
    "ChartSourcesResponse",
    "ChartsResponse",
    "Closure",
    "CloudLayer",
    "Coordinates",
    "CountriesResponse",
    "Country",
    "CountryDetail",
    "DepartureFlight",
    "DeparturesResponse",
    "DistanceResponse",
    "EnrichedAircraft",
    "EnrichedAirport",
    "FLIGHT_CATEGORIES",
    "FaaDelayResponse",
    "FlightBrief",
    "FlightBriefing",
    "FlightBriefingText",
    "FlightStatusArrival",
    "FlightStatusDeparture",
    "FlightStatusLeg",
    "FlightStatusResponse",
    "FlightTimePrediction",
    "GroundDelay",
    "GroundStop",
    "HISTORY_PLANS",
    "HistoryAirportTrafficResponse",
    "HistoryFilters",
    "HistoryFlight",
    "HistoryFlightsResponse",
    "HistoryPlan",
    "HistoryPosition",
    "HistoryPositionsResponse",
    "HistoryTrackResponse",
    "IPLocation",
    "InternalServerError",
    "Layover",
    "MemoryCache",
    "Metar",
    "MetarParsed",
    "MetarWithParsed",
    "Navaid",
    "NavaidsResponse",
    "NotFoundError",
    "NotamEntry",
    "NotamsResponse",
    "Number",
    "PermissionDeniedError",
    "PirepReport",
    "PirepsResponse",
    "Provider",
    "RateLimitError",
    "RateLimitInfo",
    "Region",
    "RegionDetail",
    "RegionsResponse",
    "RequestOptions",
    "RouteBrief",
    "RoutePair",
    "RoutePairsResponse",
    "Runway",
    "ScheduleFlight",
    "ScheduleResponse",
    "ScheduleWithStatus",
    "ServiceUnavailableError",
    "SkyLink",
    "SkyLinkError",
    "SkyLinkModel",
    "Taf",
    "TafParsed",
    "TafPeriod",
    "TafWithParsed",
    "TicketLeg",
    "TicketOffer",
    "TicketSearchResponse",
    "UnprocessableEntityError",
    "ValidationErrorItem",
    "Visibility",
    "VrsRouteResult",
    "WEBHOOK_EVENTS",
    "WeatherReport",
    "Webhook",
    "WebhookEvent",
    "WebhookEventTypesResponse",
    "WebhookListResponse",
    "WebhookSubscription",
    "WebhookToggleResponse",
    "Wind",
    "WindLevel",
    "WindsAloftResponse",
    "WindsAloftStation",
    "WxCode",
    "__version__",
    "helpers",
]
