"""Models for the ``/webhooks`` endpoints — the only non-GET part of the API.

Subset/superset trap: the ``201`` body of ``POST /webhooks`` is a strict subset
of a row of ``GET /webhooks``. The list rows carry two extra delivery-health
fields (``last_triggered_at``, ``failure_count``), so :class:`WebhookSubscription`
subclasses :class:`Webhook` rather than duplicating it — exactly the pattern the
weather namespace uses for ``?parsed=true``.

``PATCH`` answers with a two-key acknowledgement (:class:`WebhookToggleResponse`)
and ``DELETE`` answers ``204`` with no body at all, which the resource turns into
``None``.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import Field

from ._base import SkyLinkModel

__all__ = [
    "Webhook",
    "WebhookEvent",
    "WebhookEventTypesResponse",
    "WebhookListResponse",
    "WebhookSubscription",
    "WebhookToggleResponse",
]


class WebhookEvent(str, Enum):
    """The six events a subscription can listen for, as an enum.

    A ``str`` enum, so a member **is** the wire string: it serialises to
    ``"status_changed"``, compares equal to it, and can be passed anywhere the
    SDK accepts an event name::

        sky.webhooks.create(
            url="https://hooks.example.com/skylink",
            event_types=[WebhookEvent.FLIGHT_DELAYED, "gate_changed"],
            filters={"flight_number": "BA117"},
        )

    The literal type
    :data:`~skylink_api.resources.webhooks.WebhookEventType` still exists and is
    still accepted — this is the discoverable, typo-proof spelling of the same
    values. Responses keep their events as plain ``str`` (see
    :attr:`Webhook.event_types`), because an event the backend adds later must
    not break parsing.

    Values come from ``VALID_EVENTS`` in the backend's
    ``services/v31/webhook_service.py``.
    """

    STATUS_CHANGED = "status_changed"
    """Catch-all: any tracked field of the flight status changed."""

    FLIGHT_DELAYED = "flight_delayed"
    """The status indicates a delay, or an actual time moved back."""

    FLIGHT_CANCELLED = "flight_cancelled"
    """The flight was cancelled."""

    FLIGHT_BOARDING = "flight_boarding"
    """Boarding is in progress."""

    FLIGHT_LANDED = "flight_landed"
    """The flight has landed / arrived."""

    GATE_CHANGED = "gate_changed"
    """A departure or arrival gate changed."""

    def __str__(self) -> str:
        """The wire value — ``str(WebhookEvent.GATE_CHANGED) == "gate_changed"``.

        Without this, Python < 3.11 formats a ``str`` enum as
        ``"WebhookEvent.GATE_CHANGED"``, which is never what you want in a URL,
        a log line or an f-string.
        """

        return str(self.value)


class Webhook(SkyLinkModel):
    """A webhook subscription as returned by ``POST /webhooks`` (``201``)."""

    id: str | None = None
    """Server generated UUID — the handle for ``update()`` and ``delete()``."""

    url: str | None = None
    """HTTPS delivery endpoint. Non-public hosts are rejected at creation time."""

    event_types: list[str] = Field(default_factory=list)
    """Subscribed events. ``str`` rather than a ``Literal`` on purpose: the
    request side is typed
    (:data:`~skylink_api.resources.webhooks.WebhookEventType`) but a value the
    backend adds later must not break parsing."""

    filters: dict[str, Any] = Field(default_factory=dict)
    """Dynamic-key map. ``flight_number`` is the only key the backend
    understands, and it is effectively required — it is normalised to upper case
    server-side, so what comes back may differ from what was sent."""

    active: bool | None = None
    """``True`` on creation. Flipped by ``update()``, and by the dispatcher
    itself after 10 consecutive delivery failures."""

    created_at: datetime | None = None
    """ISO-8601 with a UTC offset, generated by the API."""


class WebhookSubscription(Webhook):
    """A row of ``GET /webhooks`` — :class:`Webhook` plus delivery health."""

    last_triggered_at: datetime | None = None
    """Last successful delivery; ``None`` until the webhook first fires."""

    failure_count: int | None = None
    """Consecutive delivery failures. At 10 the backend sets ``active=False``."""


class WebhookListResponse(SkyLinkModel):
    """Envelope of ``GET /webhooks``.

    :meth:`~skylink_api.resources.webhooks.Webhooks.list` returns
    :attr:`webhooks` directly; this model is what the wire actually carries.
    """

    count: int = 0
    webhooks: list[WebhookSubscription] = Field(default_factory=list)


class WebhookToggleResponse(SkyLinkModel):
    """Envelope of ``PATCH /webhooks/{id}`` — the acknowledged new state only."""

    id: str | None = None
    active: bool | None = None


class WebhookEventTypesResponse(SkyLinkModel):
    """Envelope of ``GET /webhooks/events``.

    :meth:`~skylink_api.resources.webhooks.Webhooks.event_types` returns
    :attr:`event_types` directly.
    """

    event_types: list[str] = Field(default_factory=list)
    """Sorted list of the six supported events."""
